const { appointment, doctor, patient, symptom } = require("../../support/apiFactories");

function createPair(role = "ADMIN") {
  return cy.apiRequestAs(role, "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((d) => ({ p, d })));
}

describe("API - Appointments", () => {
  beforeEach(() => cy.resetApiData());

  it("US21 CT01 e US23 CT01: cria agendamento com data normalizada, status SCHEDULED e usuario responsavel", () => createPair("RECEPTIONIST").then(({ p, d }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id, scheduledAt: "2026-05-10T10:00:00-03:00" }))).then((r) => { expect(r.status).to.eq(201); expect(r.body.data.status).to.eq("SCHEDULED"); expect(r.body.data.createdByUserId).to.be.a("string"); }));
  it("US21 CT02: rejeita criacao de agendamento por falta de permissao", () => createPair().then(({ p, d }) => cy.apiRequestAs("DOCTOR", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id }))).then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
  it("US21 CT03: rejeita criacao sem campos obrigatorios", () => cy.apiRequestAs("ADMIN", "POST", "/appointments", { patientId: "1" }).then((r) => cy.apiExpectError(r, 400, "VALIDATION_ERROR")));
  it("US21 CT04 e US23 CT03: rejeita criacao com data invalida", () => createPair().then(({ p, d }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id, scheduledAt: "data-invalida" }))).then((r) => cy.apiExpectError(r, 400, "VALIDATION_ERROR")));
  it("US21 CT05: rejeita agendamento para paciente inativo", () => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "DELETE", `/patients/${p.body.data.id}`).then(() => p)).then((p) => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((d) => ({ p, d }))).then(({ p, d }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id }))).then((r) => cy.apiExpectError(r, 409, "PATIENT_INACTIVE")));
  it("US21 CT06: rejeita agendamento com medico inativo", () => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((d) => cy.apiRequestAs("ADMIN", "DELETE", `/doctors/${d.body.data.id}`).then(() => ({ p, d })))).then(({ p, d }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id }))).then((r) => cy.apiExpectError(r, 409, "DOCTOR_INACTIVE")));
  it("US22 CT01: permite selecao sem validar aderencia por triagem quando triageId nao e informado", () => createPair().then(({ p, d }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id }))).then((r) => { expect(r.status).to.eq(201); expect(r.body.data.doctorId).to.be.a("string"); }));
  it("US22 CT02: permite selecao do medico compativel com a triagem do mesmo paciente", () => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ specialty: "Cardiologia" })).then((s) => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ specialty: "Cardiologia" })).then((d) => cy.apiRequestAs("ADMIN", "POST", "/triages", { patientId: p.body.data.id, symptomIds: [s.body.data.id] }).then((t) => ({ p, d, t }))))).then(({ p, d, t }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id, triageId: t.body.data.id }))).then((r) => { expect(r.status).to.eq(201); expect(r.body.data.triageId).to.be.a("string"); }));
  it("US22 CT03: rejeita quando a triagem pertence a outro paciente", () => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p1) => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p2) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ specialty: "Cardiologia" })).then((s) => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ specialty: "Cardiologia" })).then((d) => cy.apiRequestAs("ADMIN", "POST", "/triages", { patientId: p2.body.data.id, symptomIds: [s.body.data.id] }).then((t) => ({ p1, d, t })))))).then(({ p1, d, t }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ patientId: p1.body.data.id, doctorId: d.body.data.id, triageId: t.body.data.id }))).then((r) => cy.apiExpectError(r, 409, "TRIAGE_PATIENT_MISMATCH")));
  it("US22 CT04: rejeita quando a especialidade do medico diverge da triagem", () => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ specialty: "Cardiologia" })).then((s) => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ specialty: "Dermatologia" })).then((d) => cy.apiRequestAs("ADMIN", "POST", "/triages", { patientId: p.body.data.id, symptomIds: [s.body.data.id] }).then((t) => ({ p, d, t }))))).then(({ p, d, t }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id, triageId: t.body.data.id }))).then((r) => cy.apiExpectError(r, 409, "DOCTOR_SPECIALTY_MISMATCH")));
  it("US23 CT02: rejeita por conflito de horario", () => createPair().then(({ p, d }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id, scheduledAt: "2026-05-10T10:00:00.000Z" })).then(() => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p2) => ({ d, p2 })))).then(({ d, p2 }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/appointments", appointment({ patientId: p2.body.data.id, doctorId: d.body.data.id, scheduledAt: "2026-05-10T10:00:00.000Z" }))).then((r) => cy.apiExpectError(r, 409, "APPOINTMENT_CONFLICT")));
  it("US24 CT01: permite listar e consultar agendamentos", () => createPair("RECEPTIONIST").then(({ p, d }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id })).then((a) => cy.apiRequestAs("RECEPTIONIST", "GET", "/appointments").then((l) => ({ a, l })))).then(({ a, l }) => { expect(l.body.data).to.have.length(1); return cy.apiRequestAs("RECEPTIONIST", "GET", `/appointments/${a.body.data.id}`); }).then((r) => expect(r.status).to.eq(200)));
  it("US24 CT02: rejeita consulta de agendamentos por perfil nao autorizado", () => cy.apiRequestAs("DOCTOR", "GET", "/appointments").then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
  it("US24 CT03: aplica filtros na consulta de agendamentos", () => createPair().then(({ p, d }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ patientId: p.body.data.id, doctorId: d.body.data.id, scheduledAt: "2026-05-10T10:00:00.000Z" })).then((a) => cy.apiRequestAs("ADMIN", "GET", `/appointments?doctorId=${d.body.data.id}&scheduledFrom=2026-05-10T00:00:00.000Z&scheduledTo=2026-05-10T23:59:59.999Z`).then((r) => ({ a, r })))).then(({ a, r }) => { expect(r.status).to.eq(200); expect(r.body.data[0].id).to.eq(a.body.data.id); }));
  it("US24 CT04: retorna nao encontrado ao consultar agendamento inexistente", () => cy.apiRequestAs("ADMIN", "GET", "/appointments/999").then((r) => cy.apiExpectError(r, 404, "APPOINTMENT_NOT_FOUND")));
});
