const { appointment, doctor, patient } = require("../../support/apiFactories");

describe("API - Doctors", () => {
  beforeEach(() => cy.resetApiData());

  it("US13 CT01: cria medico com CRM unico", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((r) => { expect(r.status).to.eq(201); expect(r.body.data.crm).to.match(/^CRM-SP-/); }));
  it("US13 CT02: rejeita criacao de medico por falta de permissao", () => cy.apiRequestAs("RECEPTIONIST", "POST", "/doctors", doctor()).then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
  it("US13 CT03: rejeita criacao sem campos obrigatorios", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", { name: "Medico" }).then((r) => cy.apiExpectError(r, 400, "VALIDATION_ERROR")));
  it("US13 CT04: rejeita criacao com CRM duplicado", () => { const d = doctor({ crm: "CRM-SP-111111" }); cy.apiRequestAs("ADMIN", "POST", "/doctors", d).then(() => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ crm: d.crm }))).then((r) => cy.apiExpectError(r, 409, "DOCTOR_CRM_ALREADY_EXISTS")); });
  it("US14 CT01: permite listar e consultar medicos", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((c) => cy.apiRequestAs("ADMIN", "GET", "/doctors").then((l) => ({ c, l }))).then(({ c, l }) => { expect(l.body.data).to.have.length(1); return cy.apiRequestAs("ADMIN", "GET", `/doctors/${c.body.data.id}`); }).then((r) => expect(r.status).to.eq(200)));
  it("US14 CT02: rejeita consulta de medicos por perfil nao admin", () => cy.apiRequestAs("RECEPTIONIST", "GET", "/doctors").then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
  it("US14 CT03: retorna apenas medicos ativos por padrao", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ name: "Ativo" })).then(() => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ crm: "CRM-SP-999999" })).then((d) => cy.apiRequestAs("ADMIN", "DELETE", `/doctors/${d.body.data.id}`))).then(() => cy.apiRequestAs("ADMIN", "GET", "/doctors")).then((r) => { expect(r.body.data).to.have.length(1); expect(r.body.data[0].name).to.eq("Ativo"); }));
  it("US14 CT04: retorna nao encontrado ao consultar medico inexistente", () => cy.apiRequestAs("ADMIN", "GET", "/doctors/999").then((r) => cy.apiExpectError(r, 404, "DOCTOR_NOT_FOUND")));
  it("US15 CT01: atualiza medico mantendo CRM unico", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((d) => cy.apiRequestAs("ADMIN", "PUT", `/doctors/${d.body.data.id}`, { name: "Atualizada", specialty: "Neurologia" })).then((r) => { expect(r.status).to.eq(200); expect(r.body.data.specialty).to.eq("Neurologia"); }));
  it("US15 CT02: rejeita atualizacao de medico por falta de permissao", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((d) => cy.apiRequestAs("RECEPTIONIST", "PUT", `/doctors/${d.body.data.id}`, { specialty: "Pediatria" })).then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
  it("US15 CT03: rejeita atualizacao com CRM duplicado", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ crm: "CRM-SP-111111" })).then((first) => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor({ crm: "CRM-SP-222222" })).then(() => first)).then((first) => cy.apiRequestAs("ADMIN", "PUT", `/doctors/${first.body.data.id}`, { crm: "CRM-SP-222222" })).then((r) => cy.apiExpectError(r, 409, "DOCTOR_CRM_ALREADY_EXISTS")));
  it("US16 CT01: inativa medico e impede novo agendamento", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((d) => cy.apiRequestAs("ADMIN", "DELETE", `/doctors/${d.body.data.id}`).then(() => d)).then((d) => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p) => ({ d, p }))).then(({ d, p }) => cy.apiRequestAs("ADMIN", "POST", "/appointments", appointment({ doctorId: d.body.data.id, patientId: p.body.data.id }))).then((r) => cy.apiExpectError(r, 409, "DOCTOR_INACTIVE")));
  it("US16 CT02: rejeita inativacao de medico por perfil nao admin", () => cy.apiRequestAs("ADMIN", "POST", "/doctors", doctor()).then((d) => cy.apiRequestAs("RECEPTIONIST", "DELETE", `/doctors/${d.body.data.id}`)).then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
});
