const { patient, symptom } = require("../../support/apiFactories");

describe("API - Triages", () => {
  beforeEach(() => cy.resetApiData());

  it("US17 CT01 e US20 CT01: registra triagem desconsiderando IDs duplicados e persiste resultado consolidado", () => {
    cy.apiRequestAs("RECEPTIONIST", "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "HIGH", specialty: "Cardiologia" })).then((s) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "MEDIUM", specialty: "Clinico Geral" })).then((s2) => ({ p, s, s2 })))).then(({ p, s, s2 }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/triages", { patientId: p.body.data.id, symptomIds: [s.body.data.id, s.body.data.id, s2.body.data.id], notes: "Triagem Cypress" })).then((r) => { expect(r.status).to.eq(201); expect(r.body.data.symptomIds).to.have.length(2); expect(r.body.data.suggestedSpecialty).to.eq("Cardiologia"); expect(r.body.data.priority).to.eq("HIGH"); });
  });
  it("US17 CT02: rejeita registro de triagem por falta de permissao", () => cy.apiRequestAs("DOCTOR", "POST", "/triages", { patientId: "1", symptomIds: ["1"] }).then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
  it("US17 CT03: rejeita triagem para paciente inativo", () => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "DELETE", `/patients/${p.body.data.id}`).then(() => p)).then((p) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom()).then((s) => ({ p, s }))).then(({ p, s }) => cy.apiRequestAs("ADMIN", "POST", "/triages", { patientId: p.body.data.id, symptomIds: [s.body.data.id] })).then((r) => cy.apiExpectError(r, 409, "PATIENT_INACTIVE")));
  it("US17 CT04: rejeita triagem com sintoma inativo", () => cy.apiRequestAs("ADMIN", "POST", "/patients", patient()).then((p) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom()).then((s) => cy.apiRequestAs("ADMIN", "DELETE", `/symptoms/${s.body.data.id}`).then(() => ({ p, s })))).then(({ p, s }) => cy.apiRequestAs("ADMIN", "POST", "/triages", { patientId: p.body.data.id, symptomIds: [s.body.data.id] })).then((r) => cy.apiExpectError(r, 409, "SYMPTOM_INACTIVE")));
  it("US17 CT05 e US20 CT03: rejeita triagem sem dados essenciais", () => cy.apiRequestAs("RECEPTIONIST", "POST", "/triages", { patientId: "" }).then((r) => cy.apiExpectError(r, 400, "VALIDATION_ERROR")));
  it("US18 CT01: retorna especialidade com maior soma de pesos", () => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "CRITICAL", specialty: "Cardiologia" })).then((s) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "LOW", specialty: "Pneumologia" })).then((s2) => ({ s, s2 }))).then(({ s, s2 }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/triages/specialty-consult", { symptomIds: [s.body.data.id, s2.body.data.id] })).then((r) => { expect(r.status).to.eq(200); expect(r.body.data.suggestedSpecialty).to.eq("Cardiologia"); }));
  it("US18 CT02 e US19 CT02: rejeita consulta de especialidade por falta de permissao", () => cy.apiRequestAs("DOCTOR", "POST", "/triages/specialty-consult", { symptomIds: ["1"] }).then((r) => cy.apiExpectError(r, 403, "FORBIDDEN")));
  it("US18 CT03: rejeita consulta com symptomIds invalido", () => cy.apiRequestAs("ADMIN", "POST", "/triages/specialty-consult", { symptomIds: [] }).then((r) => cy.apiExpectError(r, 400, "VALIDATION_ERROR")));
  it("US18 CT04: desempata especialidade por ordem alfabetica", () => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "HIGH", specialty: "Dermatologia" })).then((d) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "HIGH", specialty: "Cardiologia" })).then((c) => ({ d, c }))).then(({ d, c }) => cy.apiRequestAs("ADMIN", "POST", "/triages/specialty-consult", { symptomIds: [d.body.data.id, c.body.data.id] })).then((r) => { expect(r.status).to.eq(200); expect(r.body.data.suggestedSpecialty).to.eq("Cardiologia"); }));
  it("US19 CT01: retorna a maior severidade entre os sintomas informados", () => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "LOW", specialty: "Clinico Geral" })).then((l) => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom({ severity: "CRITICAL", specialty: "Pneumologia" })).then((c) => ({ l, c }))).then(({ l, c }) => cy.apiRequestAs("RECEPTIONIST", "POST", "/triages/specialty-consult", { symptomIds: [l.body.data.id, c.body.data.id] })).then((r) => { expect(r.status).to.eq(200); expect(r.body.data.priority).to.eq("CRITICAL"); }));
  it("US19 CT03: rejeita consulta de prioridade quando o sintoma esta inativo", () => cy.apiRequestAs("ADMIN", "POST", "/symptoms", symptom()).then((s) => cy.apiRequestAs("ADMIN", "DELETE", `/symptoms/${s.body.data.id}`).then(() => s)).then((s) => cy.apiRequestAs("ADMIN", "POST", "/triages/specialty-consult", { symptomIds: [s.body.data.id] })).then((r) => cy.apiExpectError(r, 409, "SYMPTOM_INACTIVE")));
});
